In [5]:
import pandas as pd

In [6]:
import requests

In [8]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=0877e7b1fce5ef12519e8851918ffb11&language=en-US&page=1')

In [14]:
df=pd.DataFrame(response.json()['results'])[['id','title','release_date','vote_average','overview','popularity']]

In [15]:
df

,id,title,release_date,vote_average,overview,popularity
0,19404,Dilwale Dulhania Le Jayenge,1995-10-20,8.7,"Raj is a rich, carefree, happy-go-lucky second...",30.944
1,724089,Gabriel's Inferno Part II,2020-07-31,8.7,Professor Gabriel Emerson finally learns the t...,8.431
2,278,The Shawshank Redemption,1994-09-23,8.7,Framed in the 1940s for the double murder of h...,48.309
3,238,The Godfather,1972-03-14,8.7,"Spanning the years 1945 to 1955, a chronicle o...",47.556
4,761053,Gabriel's Inferno Part III,2020-11-19,8.7,The final part of the film adaption of the ero...,26.571
5,696374,Gabriel's Inferno,2020-05-29,8.7,An intriguing and sinful exploration of seduct...,9.135
6,424,Schindler's List,1993-11-30,8.6,The true story of how businessman Oskar Schind...,34.014
7,615457,Nobody,2021-03-18,8.6,"Hutch Mansell, a suburban dad, overlooked husb...",985.351
8,240,The Godfather: Part II,1974-12-20,8.6,In the continuing saga of the Corleone crime f...,34.013
9,372058,Your Name.,2016-08-26,8.6,High schoolers Mitsuha and Taki are complete s...,81.889
10,791373,Zack Snyder's Justice League,2021-03-18,8.5,Determined to ensure Superman's ultimate sacri...,2356.754
11,129,Spirited Away,2001-07-20,8.5,"A young girl, Chihiro, becomes trapped in a st...",48.675
12,441130,Wolfwalkers,2020-10-26,8.5,"In a time of superstition and magic, when wolv...",29.138
13,496243,Parasite,2019-05-30,8.5,"All unemployed, Ki-taek's family takes peculia...",128.047
14,497,The Green Mile,1999-12-10,8.5,A supernatural tale set on death row in a Sout...,39.436
15,644479,Dedicated to my ex,2019-11-01,8.5,"The film tells the story of Ariel, a 21-year-o...",22.268
16,556574,Hamilton,2020-07-03,8.5,Presenting the tale of American founding fathe...,24.707
17,680,Pulp Fiction,1994-09-10,8.5,"A burger-loving hit man, his philosophical par...",42.496
18,447362,Life in a Year,2020-11-27,8.5,A 17 year old finds out that his girlfriend is...,149.355
19,389,12 Angry Men,1957-04-10,8.5,The defense and the prosecution have rested an...,20.424

In [16]:
df=pd.DataFrame()

In [17]:
df

Empty DataFrame
Columns: []
Index: []

In [18]:
for i in range (1,429):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=0877e7b1fce5ef12519e8851918ffb11&language=en-US&page={}'.format(i))
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','release_date','vote_average','overview','popularity']]
    df = df.append(temp_df,ignore_index=True)

In [19]:
df

,id,title,release_date,vote_average,overview,popularity
0,19404,Dilwale Dulhania Le Jayenge,1995-10-20,8.7,"Raj is a rich, carefree, happy-go-lucky second...",30.944
1,724089,Gabriel's Inferno Part II,2020-07-31,8.7,Professor Gabriel Emerson finally learns the t...,8.431
2,278,The Shawshank Redemption,1994-09-23,8.7,Framed in the 1940s for the double murder of h...,48.309
3,238,The Godfather,1972-03-14,8.7,"Spanning the years 1945 to 1955, a chronicle o...",47.556
4,761053,Gabriel's Inferno Part III,2020-11-19,8.7,The final part of the film adaption of the ero...,26.571
...,...,...,...,...,...,...
8555,455551,The Recall,2017-06-02,4.4,When five friends vacation at a remote lake ho...,31.292
8556,166424,Fantastic Four,2015-08-05,4.4,Four young outsiders teleport to a dangerous u...,31.082
8557,401546,The Dinner,2017-05-05,4.4,Two brothers and their wives meet up at a haut...,14.876
8558,15268,Street Fighter: The Legend of Chun-Li,2009-02-27,4.4,"When a teenager, Chun-Li witnesses the kidnapp...",15.417
8559,11692,The Adventures of Pluto Nash,2002-08-15,4.4,"The year is 2087, the setting is the moon. Plu...",10.525